version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine
    container_name: web_service_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d web_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: